# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_Dictionary_constructor_empty <- function() {
    .Call('_flashlighttext_cpp_Dictionary_constructor_empty', PACKAGE = 'flashlighttext')
}

cpp_Dictionary_constructor_string <- function(filename) {
    .Call('_flashlighttext_cpp_Dictionary_constructor_string', PACKAGE = 'flashlighttext', filename)
}

cpp_Dictionary_constructor_vector_string <- function(tkns) {
    .Call('_flashlighttext_cpp_Dictionary_constructor_vector_string', PACKAGE = 'flashlighttext', tkns)
}

cpp_Dictionary_entry_size <- function(obj) {
    .Call('_flashlighttext_cpp_Dictionary_entry_size', PACKAGE = 'flashlighttext', obj)
}

cpp_Dictionary_index_size <- function(obj) {
    .Call('_flashlighttext_cpp_Dictionary_index_size', PACKAGE = 'flashlighttext', obj)
}

cpp_Dictionary_add_entry_entry <- function(obj, entry) {
    invisible(.Call('_flashlighttext_cpp_Dictionary_add_entry_entry', PACKAGE = 'flashlighttext', obj, entry))
}

cpp_Dictionary_add_entry_entry_idx <- function(obj, entry, idx) {
    invisible(.Call('_flashlighttext_cpp_Dictionary_add_entry_entry_idx', PACKAGE = 'flashlighttext', obj, entry, idx))
}

cpp_Dictionary_get_entry <- function(obj, idx) {
    .Call('_flashlighttext_cpp_Dictionary_get_entry', PACKAGE = 'flashlighttext', obj, idx)
}

cpp_Dictionary_get_index <- function(obj, entry) {
    .Call('_flashlighttext_cpp_Dictionary_get_index', PACKAGE = 'flashlighttext', obj, entry)
}

cpp_Dictionary_contains <- function(obj, entry) {
    .Call('_flashlighttext_cpp_Dictionary_contains', PACKAGE = 'flashlighttext', obj, entry)
}

cpp_Dictionary_pack_replabels <- function(tokens, obj, maxReps) {
    .Call('_flashlighttext_cpp_Dictionary_pack_replabels', PACKAGE = 'flashlighttext', tokens, obj, maxReps)
}

cpp_Dictionary_unpack_replabels <- function(tokens, obj, maxReps) {
    .Call('_flashlighttext_cpp_Dictionary_unpack_replabels', PACKAGE = 'flashlighttext', tokens, obj, maxReps)
}

cpp_Dictionary_set_default_index <- function(obj, idx) {
    invisible(.Call('_flashlighttext_cpp_Dictionary_set_default_index', PACKAGE = 'flashlighttext', obj, idx))
}

cpp_Dictionary_is_contiguous <- function(obj) {
    .Call('_flashlighttext_cpp_Dictionary_is_contiguous', PACKAGE = 'flashlighttext', obj)
}

cpp_Dictionary_map_entries_to_indices <- function(obj, entries) {
    .Call('_flashlighttext_cpp_Dictionary_map_entries_to_indices', PACKAGE = 'flashlighttext', obj, entries)
}

cpp_Dictionary_map_indices_to_entries <- function(obj, indices) {
    .Call('_flashlighttext_cpp_Dictionary_map_indices_to_entries', PACKAGE = 'flashlighttext', obj, indices)
}

cpp_load_words2 <- function(filename, maxWords) {
    .Call('_flashlighttext_cpp_load_words2', PACKAGE = 'flashlighttext', filename, maxWords)
}

cpp_create_word_dict <- function(ptr, lexicon) {
    .Call('_flashlighttext_cpp_create_word_dict', PACKAGE = 'flashlighttext', ptr, lexicon)
}

cpp_KenLM_constructor <- function(path, ptr) {
    .Call('_flashlighttext_cpp_KenLM_constructor', PACKAGE = 'flashlighttext', path, ptr)
}

cpp_KenLM_start <- function(obj, startWithNothing) {
    .Call('_flashlighttext_cpp_KenLM_start', PACKAGE = 'flashlighttext', obj, startWithNothing)
}

cpp_KenLM_score <- function(obj, state, usrTokenIdx) {
    .Call('_flashlighttext_cpp_KenLM_score', PACKAGE = 'flashlighttext', obj, state, usrTokenIdx)
}

cpp_KenLM_finish <- function(obj, state) {
    .Call('_flashlighttext_cpp_KenLM_finish', PACKAGE = 'flashlighttext', obj, state)
}

cpp_LexiconDecoderOptions_constructor <- function(beamSize, beamSizeToken, beamThreshold, lmWeight, wordScore, unkScore, silScore, logAdd, criterionType) {
    .Call('_flashlighttext_cpp_LexiconDecoderOptions_constructor', PACKAGE = 'flashlighttext', beamSize, beamSizeToken, beamThreshold, lmWeight, wordScore, unkScore, silScore, logAdd, criterionType)
}

cpp_LexiconDecoderOptions_set_beamSize <- function(obj, value) {
    invisible(.Call('_flashlighttext_cpp_LexiconDecoderOptions_set_beamSize', PACKAGE = 'flashlighttext', obj, value))
}

cpp_LexiconDecoderOptions_get_beamSize <- function(obj) {
    .Call('_flashlighttext_cpp_LexiconDecoderOptions_get_beamSize', PACKAGE = 'flashlighttext', obj)
}

cpp_LexiconDecoderOptions_set_beamSizeToken <- function(obj, value) {
    invisible(.Call('_flashlighttext_cpp_LexiconDecoderOptions_set_beamSizeToken', PACKAGE = 'flashlighttext', obj, value))
}

cpp_LexiconDecoderOptions_get_beamSizeToken <- function(obj) {
    .Call('_flashlighttext_cpp_LexiconDecoderOptions_get_beamSizeToken', PACKAGE = 'flashlighttext', obj)
}

cpp_LexiconDecoderOptions_set_beamThreshold <- function(obj, value) {
    invisible(.Call('_flashlighttext_cpp_LexiconDecoderOptions_set_beamThreshold', PACKAGE = 'flashlighttext', obj, value))
}

cpp_LexiconDecoderOptions_get_beamThreshold <- function(obj) {
    .Call('_flashlighttext_cpp_LexiconDecoderOptions_get_beamThreshold', PACKAGE = 'flashlighttext', obj)
}

cpp_LexiconDecoderOptions_set_lmWeight <- function(obj, value) {
    invisible(.Call('_flashlighttext_cpp_LexiconDecoderOptions_set_lmWeight', PACKAGE = 'flashlighttext', obj, value))
}

cpp_LexiconDecoderOptions_get_lmWeight <- function(obj) {
    .Call('_flashlighttext_cpp_LexiconDecoderOptions_get_lmWeight', PACKAGE = 'flashlighttext', obj)
}

cpp_LexiconDecoderOptions_set_wordScore <- function(obj, value) {
    invisible(.Call('_flashlighttext_cpp_LexiconDecoderOptions_set_wordScore', PACKAGE = 'flashlighttext', obj, value))
}

cpp_LexiconDecoderOptions_get_wordScore <- function(obj) {
    .Call('_flashlighttext_cpp_LexiconDecoderOptions_get_wordScore', PACKAGE = 'flashlighttext', obj)
}

cpp_LexiconDecoderOptions_set_unkScore <- function(obj, value) {
    invisible(.Call('_flashlighttext_cpp_LexiconDecoderOptions_set_unkScore', PACKAGE = 'flashlighttext', obj, value))
}

cpp_LexiconDecoderOptions_get_unkScore <- function(obj) {
    .Call('_flashlighttext_cpp_LexiconDecoderOptions_get_unkScore', PACKAGE = 'flashlighttext', obj)
}

cpp_LexiconDecoderOptions_set_silScore <- function(obj, value) {
    invisible(.Call('_flashlighttext_cpp_LexiconDecoderOptions_set_silScore', PACKAGE = 'flashlighttext', obj, value))
}

cpp_LexiconDecoderOptions_get_silScore <- function(obj) {
    .Call('_flashlighttext_cpp_LexiconDecoderOptions_get_silScore', PACKAGE = 'flashlighttext', obj)
}

cpp_LexiconDecoderOptions_set_logAdd <- function(obj, value) {
    invisible(.Call('_flashlighttext_cpp_LexiconDecoderOptions_set_logAdd', PACKAGE = 'flashlighttext', obj, value))
}

cpp_LexiconDecoderOptions_get_logAdd <- function(obj) {
    .Call('_flashlighttext_cpp_LexiconDecoderOptions_get_logAdd', PACKAGE = 'flashlighttext', obj)
}

cpp_LexiconDecoderOptions_set_CriterionType <- function(obj, value) {
    invisible(.Call('_flashlighttext_cpp_LexiconDecoderOptions_set_CriterionType', PACKAGE = 'flashlighttext', obj, value))
}

cpp_LexiconDecoderOptions_get_CriterionType <- function(obj) {
    .Call('_flashlighttext_cpp_LexiconDecoderOptions_get_CriterionType', PACKAGE = 'flashlighttext', obj)
}

cpp_Trie_constructor <- function(maxChildren, rootIdx) {
    .Call('_flashlighttext_cpp_Trie_constructor', PACKAGE = 'flashlighttext', maxChildren, rootIdx)
}

cpp_Trie_getRoot <- function(obj) {
    .Call('_flashlighttext_cpp_Trie_getRoot', PACKAGE = 'flashlighttext', obj)
}

cpp_Trie_insert <- function(obj, indices, label, score) {
    .Call('_flashlighttext_cpp_Trie_insert', PACKAGE = 'flashlighttext', obj, indices, label, score)
}

cpp_Trie_search <- function(obj, indices) {
    .Call('_flashlighttext_cpp_Trie_search', PACKAGE = 'flashlighttext', obj, indices)
}

cpp_Trie_smear <- function(obj, smear_mode) {
    invisible(.Call('_flashlighttext_cpp_Trie_smear', PACKAGE = 'flashlighttext', obj, smear_mode))
}

cpp_TrieNode_constructor <- function(idx) {
    .Call('_flashlighttext_cpp_TrieNode_constructor', PACKAGE = 'flashlighttext', idx)
}

cpp_TrieNode_maxScore <- function(obj) {
    .Call('_flashlighttext_cpp_TrieNode_maxScore', PACKAGE = 'flashlighttext', obj)
}

