# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_Dictionary_create_empty <- function() {
    .Call(`_flashlighttext_cpp_Dictionary_create_empty`)
}

cpp_Dictionary_create_string <- function(filename) {
    .Call(`_flashlighttext_cpp_Dictionary_create_string`, filename)
}

cpp_Dictionary_create_vector_string <- function(tkns) {
    .Call(`_flashlighttext_cpp_Dictionary_create_vector_string`, tkns)
}

cpp_Dictionary_entry_size <- function(ptr) {
    .Call(`_flashlighttext_cpp_Dictionary_entry_size`, ptr)
}

cpp_Dictionary_index_size <- function(ptr) {
    .Call(`_flashlighttext_cpp_Dictionary_index_size`, ptr)
}

cpp_Dictionary_add_entry_entry <- function(ptr, entry) {
    invisible(.Call(`_flashlighttext_cpp_Dictionary_add_entry_entry`, ptr, entry))
}

cpp_Dictionary_add_entry_entry_idx <- function(ptr, entry, idx) {
    invisible(.Call(`_flashlighttext_cpp_Dictionary_add_entry_entry_idx`, ptr, entry, idx))
}

cpp_Dictionary_get_entry <- function(ptr, idx) {
    .Call(`_flashlighttext_cpp_Dictionary_get_entry`, ptr, idx)
}

cpp_Dictionary_get_index <- function(ptr, entry) {
    .Call(`_flashlighttext_cpp_Dictionary_get_index`, ptr, entry)
}

cpp_Dictionary_contains <- function(ptr, entry) {
    .Call(`_flashlighttext_cpp_Dictionary_contains`, ptr, entry)
}

cpp_Dictionary_pack_replabels <- function(tokens, ptr, maxReps) {
    .Call(`_flashlighttext_cpp_Dictionary_pack_replabels`, tokens, ptr, maxReps)
}

cpp_Dictionary_unpack_replabels <- function(tokens, ptr, maxReps) {
    .Call(`_flashlighttext_cpp_Dictionary_unpack_replabels`, tokens, ptr, maxReps)
}

cpp_Dictionary_set_default_index <- function(ptr, idx) {
    invisible(.Call(`_flashlighttext_cpp_Dictionary_set_default_index`, ptr, idx))
}

cpp_Dictionary_is_contiguous <- function(ptr) {
    .Call(`_flashlighttext_cpp_Dictionary_is_contiguous`, ptr)
}

cpp_Dictionary_map_entries_to_indices <- function(ptr, entries) {
    .Call(`_flashlighttext_cpp_Dictionary_map_entries_to_indices`, ptr, entries)
}

cpp_Dictionary_map_indices_to_entries <- function(ptr, indices) {
    .Call(`_flashlighttext_cpp_Dictionary_map_indices_to_entries`, ptr, indices)
}

cpp_load_words <- function(filename, maxWords) {
    .Call(`_flashlighttext_cpp_load_words`, filename, maxWords)
}

cpp_create_word_dict <- function(lexicon) {
    .Call(`_flashlighttext_cpp_create_word_dict`, lexicon)
}

